"""Turn a FiveM resource folder into one Lua file the ASI plugin can run."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field

from .manifest import Manifest, expand_globs

# exports('name', fn)  /  exports["name"] = fn
_EXPORT_CALL = re.compile(r"""\bexports\s*\(\s*(['"])(.+?)\1\s*,""")

# Things with no single-player meaning at all. We warn rather than delete.
SUSPECT_PATTERNS = [
    (re.compile(r"\bMySQL\b|\boxmysql\b|\bexports\.ghmattimysql\b"), "database access"),
    (re.compile(r"\bPerformHttpRequest\b"), "HTTP request"),
    (re.compile(r"\bESX\b"), "ESX framework dependency"),
    (re.compile(r"\bQBCore\b|\bQBX\b"), "QBCore framework dependency"),
    (re.compile(r"\bSendNUIMessage\b|\bSetNuiFocus\b"), "NUI / HTML interface"),
    (re.compile(r"\bRegisterNUICallback\b"), "NUI callback"),
    (re.compile(r"\bGetPlayerIdentifier\w*\b"), "player identifiers"),
]


@dataclass
class BundleResult:
    resource: str
    out_path: str
    script_count: int
    server_count: int
    warnings: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


def wrap_shim(source: str) -> str:
    """Inline the shim as an immediately-invoked chunk.

    The shim ends in `return shim`. A bare `return` at the top level of a
    Lua chunk terminates it, so pasting the file in raw would make every
    line after it unreachable (and a syntax error). Wrapping it in a
    function keeps the return local to the shim.
    """
    return "local shim = (function()\n" + source + "\nend)()\n"


def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def _scan_suspects(src: str, rel: str, warnings: list[str]) -> None:
    for rx, label in SUSPECT_PATTERNS:
        if rx.search(src):
            msg = f"{rel}: uses {label} - will not work in SP without editing"
            if msg not in warnings:
                warnings.append(msg)


def _rewrite(src: str, resource: str) -> str:
    """Minimal source rewrites that the shim cannot handle at runtime."""
    src = _EXPORT_CALL.sub(
        lambda m: f"exports__register('{resource}', {m.group(1)}{m.group(2)}{m.group(1)},",
        src,
    )
    return src


def bundle_resource(
    mf: Manifest,
    out_dir: str,
    shim_source: str,
    include_server: bool = True,
    inline_shim: bool = True,
) -> BundleResult:
    resource_dir = os.path.dirname(os.path.abspath(mf.path))
    warnings: list[str] = []
    notes: list[str] = []

    for pat in mf.raw_directives.get("client_scripts", []) + mf.raw_directives.get("client_script", []):
        if pat.startswith("@"):
            notes.append(f"cross-resource include '{pat}' - convert that resource too and load it first")

    client_files = expand_globs(resource_dir, mf.all_scripts)
    server_files = expand_globs(resource_dir, mf.server_scripts) if include_server else []

    parts: list[str] = []
    parts.append(f"-- Generated by fivem2sp from resource '{mf.resource_name}'")
    parts.append("-- Do not edit here; edit the original resource and re-run the converter.\n")

    if inline_shim:
        parts.append("-- ============ begin fivem_shim ============")
        parts.append(wrap_shim(shim_source))
        parts.append("-- ============  end fivem_shim  ============\n")
    else:
        parts.append('local shim = dofile("scripts/addins/fivem_shim.lua")\n')

    parts.append(f'shim.current_resource = "{mf.resource_name}"\n')

    if server_files:
        parts.append('shim.side = "server"')
        for f in server_files:
            rel = os.path.relpath(f, resource_dir).replace("\\", "/")
            src = _read(f)
            _scan_suspects(src, rel, warnings)
            parts.append(f"\n-- ---- [server] {rel} ----\ndo\n{_rewrite(src, mf.resource_name)}\nend")
        parts.append('\nshim.side = "client"\n')

    for f in client_files:
        rel = os.path.relpath(f, resource_dir).replace("\\", "/")
        src = _read(f)
        _scan_suspects(src, rel, warnings)
        parts.append(f"\n-- ---- [client] {rel} ----\ndo\n{_rewrite(src, mf.resource_name)}\nend")

    parts.append(_TICK_FOOTER)

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{mf.resource_name}.lua")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(parts))

    return BundleResult(
        resource=mf.resource_name,
        out_path=out_path,
        script_count=len(client_files),
        server_count=len(server_files),
        warnings=warnings,
        notes=notes,
    )


_TICK_FOOTER = """
-- ===================================================================
-- Frame pump. The Lua plugin calls tick() once per frame; that is what
-- drives every Citizen.CreateThread in the resource above.
-- ===================================================================
local __first_tick = true

function tick()
    if __first_tick then
        __first_tick = false
        shim.notify("loaded: " .. shim.current_resource, 5000)
    end
    shim.pump()
    shim.draw_notifications()
end

-- LuaV and some forks look for these names instead.
OnTick = tick
update = tick
"""
