"""Emit a Lua script that rebuilds a ymap at runtime with CREATE_OBJECT.

This is the part that lets you skip OpenIV entirely. Instead of packing
the ymap into a dlc.rpf so the streamer mounts it, we read the entity
list at build time and spawn each prop in-game, frozen in place, with
distance-based streaming so you are not holding 4000 objects at once.

The catch, stated plainly: this only works for archetypes the game
already has. A prop that ships inside the resource's stream/ folder as a
custom .ydr has no archetype registered, so CREATE_OBJECT returns 0 for
it. The converter reports those by name so you know exactly which ones
still need real asset mounting.
"""

from __future__ import annotations

import os

from .bundler import wrap_shim
from .ymap import MapData


def _lua_num(v: float) -> str:
    return f"{v:.4f}"


def generate_map_lua(
    maps: list[MapData],
    out_dir: str,
    name: str,
    shim_source: str,
    stream_radius: float = 300.0,
    inline_shim: bool = True,
) -> tuple[str, int]:
    entities = []
    deletions = []
    for md in maps:
        entities.extend(md.entities)
        deletions.extend(md.deletions)

    rows = []
    for e in entities:
        rows.append(
            '  {{n="{arch}",x={x},y={y},z={z},rx={rx},ry={ry},rz={rz},l={l}}},'.format(
                arch=e.archetype,
                x=_lua_num(e.x),
                y=_lua_num(e.y),
                z=_lua_num(e.z),
                rx=_lua_num(e.rx),
                ry=_lua_num(e.ry),
                rz=_lua_num(e.rz),
                l=_lua_num(e.lod_dist),
            )
        )

    del_rows = [
        '  {{n="{a}",x={x},y={y},z={z}}},'.format(
            a=a, x=_lua_num(x), y=_lua_num(y), z=_lua_num(z)
        )
        for (a, x, y, z) in deletions
    ]

    head = [f"-- Generated by fivem2sp: runtime map loader for '{name}'",
            f"-- {len(entities)} entities from {len(maps)} ymap(s)\n"]

    if inline_shim:
        head.append("-- ============ begin fivem_shim ============")
        head.append(wrap_shim(shim_source))
        head.append("-- ============  end fivem_shim  ============\n")
    else:
        head.append('local shim = dofile("scripts/addins/fivem_shim.lua")\n')

    body = _TEMPLATE.replace("__MAPNAME__", name)
    body = body.replace("__RADIUS__", _lua_num(stream_radius))
    body = body.replace("__ENTITIES__", "\n".join(rows))
    body = body.replace("__DELETIONS__", "\n".join(del_rows))

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"map_{name}.lua")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(head) + "\n" + body)

    return out_path, len(entities)


_TEMPLATE = r"""
shim = shim or _G.__FIVEM_SHIM

local MAP_NAME      = "__MAPNAME__"
local STREAM_RADIUS = __RADIUS__
local UNLOAD_RADIUS = STREAM_RADIUS * 1.35
local SPAWN_BUDGET  = 8      -- objects created per frame; raise if load is slow

-- Model hashes are computed at load time via GetHashKey so the file stays
-- plain Lua (FiveM's `backtick` hash literal is not valid in every plugin).
local ENTITIES = {
__ENTITIES__
}

local DELETIONS = {
__DELETIONS__
}

for _, e in ipairs(ENTITIES) do
    e.a = GetHashKey(e.n)
    e.handle = nil
    e.failed = false
end

local spawned       = 0
local missing_models = {}
local missing_count  = 0
local hidden         = {}
local enabled        = true

local function dist2(ax, ay, az, bx, by, bz)
    local dx, dy, dz = ax - bx, ay - by, az - bz
    return dx * dx + dy * dy + dz * dz
end

local function try_spawn(e)
    if not IsModelValid(e.a) or not IsModelInCdimage(e.a) then
        e.failed = true
        if not missing_models[e.n] then
            missing_models[e.n] = true
            missing_count = missing_count + 1
        end
        return false
    end

    RequestModel(e.a)
    if not HasModelLoaded(e.a) then
        return false          -- try again next frame
    end

    local obj = CreateObjectNoOffset(e.a, e.x, e.y, e.z, false, false, false)
    if obj == 0 or not DoesEntityExist(obj) then
        e.failed = true
        return false
    end

    SetEntityRotation(obj, e.rx, e.ry, e.rz, 2, true)
    FreezeEntityPosition(obj, true)
    SetEntityAsMissionEntity(obj, true, true)
    SetEntityInvincible(obj, true)
    SetEntityLodDist(obj, math.floor(e.l))

    e.handle = obj
    spawned = spawned + 1
    SetModelAsNoLongerNeeded(e.a)
    return true
end

local function despawn(e)
    if e.handle and DoesEntityExist(e.handle) then
        DeleteObject(e.handle)
        spawned = spawned - 1
    end
    e.handle = nil
end

local function apply_deletions(px, py, pz)
    for i, d in ipairs(DELETIONS) do
        if not hidden[i] and dist2(px, py, pz, d.x, d.y, d.z) < (STREAM_RADIUS * STREAM_RADIUS) then
            CreateModelHide(d.x, d.y, d.z, 2.0, GetHashKey(d.n), false)
            hidden[i] = true
        end
    end
end

local cursor = 1

local function stream_step()
    local ped = PlayerPedId()
    if not ped or ped == 0 then return end
    local pc = GetEntityCoords(ped, true)
    local px, py, pz = pc.x, pc.y, pc.z

    apply_deletions(px, py, pz)

    local budget = SPAWN_BUDGET
    local checked = 0
    local total = #ENTITIES
    if total == 0 then return end

    while checked < total and budget > 0 do
        local e = ENTITIES[cursor]
        cursor = cursor + 1
        if cursor > total then cursor = 1 end
        checked = checked + 1

        if not e.failed then
            local d2 = dist2(px, py, pz, e.x, e.y, e.z)
            if e.handle == nil and d2 < (STREAM_RADIUS * STREAM_RADIUS) then
                if try_spawn(e) then budget = budget - 1 end
            elseif e.handle ~= nil and d2 > (UNLOAD_RADIUS * UNLOAD_RADIUS) then
                despawn(e)
                budget = budget - 1
            end
        end
    end
end

local function teleport_to_map()
    if #ENTITIES == 0 then return end
    local e = ENTITIES[1]
    local ped = PlayerPedId()
    SetEntityCoords(ped, e.x, e.y, e.z + 2.0, false, false, false, true)
    shim.notify("teleported to " .. MAP_NAME, 4000)
end

local function unload_all()
    for _, e in ipairs(ENTITIES) do despawn(e) end
    cursor = 1
    shim.notify(MAP_NAME .. " unloaded", 3000)
end

RegisterCommand("map_toggle", function()
    enabled = not enabled
    if not enabled then unload_all() end
    shim.notify(MAP_NAME .. (enabled and " enabled" or " disabled"), 3000)
end)

RegisterCommand("map_tp", function() teleport_to_map() end)

RegisterCommand("map_info", function()
    shim.notify(("%s: %d/%d live, %d unstreamable models")
        :format(MAP_NAME, spawned, #ENTITIES, missing_count), 8000)
    for n in pairs(missing_models) do
        print("[fivem2sp] no archetype in game files: " .. n)
    end
end)

CreateThread(function()
    Wait(2000)
    shim.notify(("%s ready - %d entities"):format(MAP_NAME, #ENTITIES), 6000)
    while true do
        if enabled then stream_step() end
        Wait(0)
    end
end)

CreateThread(function()
    while true do
        Wait(250)
        if enabled and missing_count > 0 then
            -- keep the count visible; these are the props that still need
            -- their assets mounted properly
        end
    end
end)

local __first_tick = true

function tick()
    if __first_tick then
        __first_tick = false
        shim.current_resource = MAP_NAME
    end
    shim.pump()
    shim.draw_notifications()
end

OnTick = tick
update = tick
"""
